## create

# GET http://localhost:3333/admin
# Content-Type: application/json

# {
# 	"email": "gustavolage200@gmail.com",
# 	"password": "06052001gl"
# }

POST  http://localhost:3333/admin/add-project
Content-Type: application/json

{
  "image": "",
	"title": "gustavolage200@gmail.com",
	"tag": "#PESSOAL",
  "description": "Projetin Fellas"
}